# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11
language: swift # objective-c
branches:
  only:
    - master

env:
  global:
    - CODECOV_TOKEN="2b79fa30-0b74-418c-8ae7-16cb24c6ac27"
    - FRAMEWORK_NAME="MJModel"
    - IOS_FRAMEWORK_SCHEME="$FRAMEWORK_NAME iOS"
    - MACOS_FRAMEWORK_SCHEME="$FRAMEWORK_NAME macOS"
    - TVOS_FRAMEWORK_SCHEME="$FRAMEWORK_NAME tvOS"
    - WATCHOS_FRAMEWORK_SCHEME="$FRAMEWORK_NAME watchOS"
    - EXAMPLE_WORKSPACE="Example/$FRAMEWORK_NAME Example.xcworkspace"
    - EXAMPLE_SCHEME="iOS Example"
  matrix:
    - DESTINATION="OS=13.0,name=iPhone XS"        SCHEME="$IOS_FRAMEWORK_SCHEME" BUILD_EXAMPLE="YES"
    - DESTINATION="OS=12.2,name=iPhone XS"        SCHEME="$IOS_FRAMEWORK_SCHEME"
    - DESTINATION="OS=11.4,name=iPhone X"         SCHEME="$IOS_FRAMEWORK_SCHEME"

    - DESTINATION="arch=x86_64"                   SCHEME="$MACOS_FRAMEWORK_SCHEME"

    - DESTINATION="OS=13.0,name=Apple TV 4K"      SCHEME="$TVOS_FRAMEWORK_SCHEME"
    - DESTINATION="OS=12.2,name=Apple TV 4K"      SCHEME="$TVOS_FRAMEWORK_SCHEME"
    - DESTINATION="OS=11.4,name=Apple TV 4K"      SCHEME="$TVOS_FRAMEWORK_SCHEME"

    - DESTINATION="OS=6.0,name=Apple Watch Series 4 - 44mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" BUILD_ONLY="YES"
    - DESTINATION="OS=5.2,name=Apple Watch Series 4 - 40mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" BUILD_ONLY="YES"
    - DESTINATION="OS=4.2,name=Apple Watch Series 3 - 42mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" BUILD_ONLY="YES"

script:
  # 有一个结果为非0，则返回非0
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - if [ $BUILD_ONLY == "YES" ]; then
      xcodebuild -project "${FRAMEWORK_NAME}.xcodeproj" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    else
      xcodebuild -enableCodeCoverage YES -project "${FRAMEWORK_NAME}.xcodeproj" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    fi

  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "$EXAMPLE_WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
